CREATE TABLE IF NOT EXISTS repositories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner TEXT NOT NULL,
    repo TEXT NOT NULL,
    default_branch TEXT DEFAULT 'main',
    description TEXT,
    overall_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_owner_repo UNIQUE (owner, repo)
);

CREATE TABLE IF NOT EXISTS files(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id BIGINT NOT NULL REFERENCES repositories(id) ON DELETE CASCADE, 
    path TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    content TEXT,
    summary TEXT,
    CONSTRAINT unique_path_per_repo UNIQUE(repo_id, path)
); 

CREATE INDEX IF NOT EXISTS idx_repos_owner_repo ON repositories (owner, repo);
CREATE INDEX IF NOT EXISTS idx_files_repo_path ON files (repo_id, path);